### ISSUE TITLE
clean up pubspec.yaml file

### ISSUE THREAD

**Issue by JordyHers** [JordyHers-org/Times-up-flutter#61]
remove unnecessary comments and sort packages by categories 

e.g:

```yaml
# ui
auto_size_text:
....
....

# domain
https:
....
....

```
